#!/bin/bash

echo starting
exec 2>&1
set -eux
eval "export HOME=~$( id -un )"
export PATH="$HOME/bin:$PATH"

cd "$( git rev-parse --show-toplevel )"

if ! [ -e ./var/live/ls/entries.json ] ; then
	mkdir -p ./var/live/ls
	exec ./with-live ./bin/ls-cache init --recursive "" ./var/live/ls
fi
exec ./with-live ./bin/ls-cache update --tail ./var/live/ls
