#!/bin/bash

echo starting
exec 2>&1
set -eux
eval "export HOME=~$( id -un )"
export PATH="$HOME/bin:$PATH"

cd "$( git rev-parse --show-toplevel )"

# mediainfo
export PATH="/opt/homebrew/bin:$PATH"

if [ -f ./var/live/mediainfo/state.json ] ; then
        exec ./with-live ./bin/mediainfo-cache --debug-limiter --debug-lister update --tail var/live/mediainfo var/live/mediainfo
else
        exec ./with-live ./bin/mediainfo-cache --debug-limiter --debug-lister init --tail --recursive "" var/live/mediainfo var/live/mediainfo
fi
