#!/bin/bash
exec 2>&1
set -eux
cd "$( git rev-parse --show-toplevel )"
mkdir -p var/live/day-db
exec ./with-live env EXIF_DB_DIR=var/live/exif LS_CACHE_DIR=var/live/ls DAY_DB_DIR=var/live/day-db yarn server
