#!/bin/bash

echo starting
exec 2>&1
set -eux
eval "export HOME=~$( id -un )"
export PATH="$HOME/bin:$PATH"

cd "$( git rev-parse --show-toplevel )"

mkdir -p var/live/day-db
exec ./with-live \
    env \
    EXIF_DB_DIR=/Users/rachel/git/github.com/blaahaj/dropbox-hacking-exif-db/var/live/exif \
    LS_CACHE_DIR=/Users/rachel/git/github.com/blaahaj/dropbox-hacking-ls-cache/var/live/ls \
    DAY_DB_DIR=var/live/day-db \
    PHOTO_DB_DIR=var/live/photo-db \
    PUBLIC_DIR=$PWD/dropbox-hacking-photo-manager-client/public \
    ./bin/photo-manager-server
